### PR TITLE
Used constants for CSS colors -Issue#14

### LINKED ISSUE #14: Use constants for CSS colors
Set SCSS constants for colors to  increase reusability and modularity

### PR DESCRIPTION
**Pull request by Inoxia25**
## What this PR does:
Adds constants for CSS colors in scss files.
## How does this PR add value
- This change improves readability and modularity, and will be further helpful for implementing the dark mode toggle feature.

### CODE REVIEW

**Comment by jagnani73** [comment]
@Inoxia25 We still are declaring the constants multiple times in various scss files, which kinda defeats the purpose
I think declaring them at the root level, ie, `/assets/css/main.scss` should work for all the nests. If it doesn't, can use core css `:root` constants

**Comment by Inoxia25** [comment]
@jagnani73 oh okay I was not sure if `/assets/css/main.css`  was being imported in all the scss files.  But the, should I change `main.css` file to `main.scss`?

**Comment by jagnani73** [comment]
@Inoxia25 lets have a 1on1 and explore it there itself?

**Comment by robzwolf** [comment]
Hey @Inoxia25! Is this pull request ready for review and merging? Or do you need more time to work on it?

**Comment by Inoxia25** [comment]
@robzwolf I need some more time to work on it, have to make some changes

**Comment by robzwolf** [comment]
> @robzwolf I need some more time to work on it, have to make some changes

Sure thing. I've marked the PR as `Draft` in the meantime. When you're ready for review, mark it as 'ready for review' and request a review from me. :)

**Review by robzwolf — APPROVED** [review]
Awesome stuff! I'm a huge fan of CSS variables, particularly for things like colours. Really impressed you managed to write this up so well!

**Pull request merged**
