### PR TITLE
Add a dropdown menu in navigation bar for smaller screens

### LINKED ISSUE #43: Add dropdown menu to navigation bar for smaller screens
Navigation bar works well for wide screens. For smaller screens, a dropdown menu to the top right corner would look good.

### PR DESCRIPTION
**Pull request by ksaisudha24**
### Why This PR Adds Value

The navigation bar is made responsive.

### What This PR Adds

- The links to different sections of the page are collapsed into a dropdown menu in smaller screens.

### Screenshot

dropdown

### How This PR Could Be Improved

- The hardcoded CSS media queries can be changed for smoother UI.
- The dropdown menu's position can be adjusted and it can be styled further.

### Issue This PR Closes

- This PR also adds links to contact and recommendations in the navbar.

This closes #43 #50

### CODE REVIEW

**Review by louisefindlay23 — CHANGES_REQUESTED** [review]
Hi, @ksaisudha24. Awesome work. Glad you got the CSS display issue sorted.

**Some suggestions:** Perhaps make the menu logo white for better contrast? It might have just been me but I found it hard to see the black menu icon on the blue background. Also, could perhaps keep the MLH logo at the top of the page rather than moved down when the dropdown menu is opened?

**Issue:** On a smaller mobile screen, I noticed there was no margin between the menu items and the right hand side.

Dropdown Menu Screenshot

**Comment by ksaisudha24** [comment]
@louisefindlay23 Thank you for your suggestions! I will work on them.

**Comment by dtemir** [comment]
@ksaisudha24 nice job! looking much better with your PR. I just wonder if we can add some padding for the MLH Logo? On smartphone screens it looks like it gets out of border.

Let me know if you need help and we can work on it together. I won't be awake until around 5 hours before the stand-up though.

iPhone X website view

**Comment by ksaisudha24** [comment]
Hey @dtemir, Thanks for the suggestion. I didn't notice it. Would love to work on it with you before the stand-up begins!

**Review by robzwolf — APPROVED** [review]
This is absolutely awesome. 👍 👍

**Pull request merged**
