### PR TITLE
Added navbar buttons + Unfinished README.md I was unable to ignore

### PR DESCRIPTION
**Pull request by Primata**
### Why This PR Adds Value
Wanted to solve issue #50 Add Recommendations and Contact Me buttons to navbar.

### What This PR Adds
Adds Recommendations and Contact Me to navbar and div ids on recommendations.html and contact.html. It also adds an unfinished README.md file which I already had locally.

* navbar.html add buttons and links to them
* recommendations.html wraps with div id="recommendations
* contact.html wraps with div id="contact"
* navbar.scss properly displays buttons to the navbar

### Screenshot
image

### How This PR Could Be Improved
css display review. #48 might have an issue #48 here if it edits how navbar displays things.

### Issue This PR Closes
This closes issue #50

### CODE REVIEW

**Comment by Primata** [comment]
@robzwolf

**Comment by louisefindlay23** [comment]
Hi, @SnowPrimate. Just responding to your Discord PM, requesting a review.

Looks great. Might be nice to add screenshots of the website and a link to the deployed web app for easy access.

The rendered MD for the directory structure looks a little strange. Not sure if it's supposed to look like this?

Directory Structure Readme

**Comment by Primata** [comment]
image
That's fixed on the other branch 🤕

**Comment by dtemir** [comment]
@SnowPrimate having a little issue here when I put the browser to half of my screen. Probably caused by the fact the **logo** is set to the center at all times.
Issue on the website. Navbar links in the right do not move when screen sized differently

**Comment by Primata** [comment]
@dtemir Shoot, that would also be an issue despite my modifications. I would say let's use justify-content: space-between? I'll fix that tomorrow as soon as I can, for sure before our meeting! Really late around here.

**Review by robzwolf — CHANGES_REQUESTED** [review]
I agree with the other comments on this PR – try to fix the white gap and then I'll review this again :)

**Comment by Primata** [comment]
@robzwolf I've discussed with @jagnani73 and he said that he and @dtemir are working on the white gap issue since they are working on the navbar's CSS. I'll wait for their solution and fix it from there if there is anything to be done. How should I proceed here? should I close this pull request and then PR again after their PR gets merged?

**Comment by robzwolf** [comment]
> @robzwolf I've discussed with @jagnani73 and he said that he and @dtemir are working on the white gap issue since they are working on the navbar's CSS. I'll wait for their solution and fix it from there if there is anything to be done. How should I proceed here? should I close this pull request and then PR again after their PR gets merged?

There are a few acceptable approaches here. I think you should mark this pull request as a Draft one (see [this guide](https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/)) and then convert it to a full PR once you're ready for review.

**Comment by robzwolf** [comment]
Hey @SnowPrimate – I've marked this PR as a Draft for you.

Can you take a look at the latest version of `main` and work out which changes are still needed? I've a feeling a lot of this PR is perhaps no longer necessary.

**Comment by Primata** [comment]
Seems like the navbar has been rebuilt, including my changes, but it has a few issues. I'll close this issue and open a new ticket to deal with those specifically.

**Pull request closed without merging**
