### PR TITLE
Added the sun moon toggle to navbar

### LINKED ISSUE #48: Improving Dark Mode Toggle
Improve the current dark mode toggle. Currently, the toggle is at the left hand side with no space between it and the edge of the browser. There's also large text that's says enable Dark Mode.

- The toggle could be moved to the the top left similar to the navigation bar 

- The toggle switch could be modified to a sun and moon icon similar to this [article](https://dev.to/shadowscientist/making-a-dark-mode-switch-lightly-249j) - there's a Github repo and Codepen inside

### PR DESCRIPTION
**Pull request by Inoxia25**
### Why This PR Adds Value

- Have changed the previous toggle to a sun moon toggle, showing a sun for the light mode and moon for the dark mode.
- Have added the toggle to the upper left corner of the navbar
- Made dark mode the default theme for the page

### What This PR Adds

- It adds a `toggle.scss` file for the css of the sun moon toggle.
- `navbar.html` was changed to change the positioning of the toggle.
- `assets/js/dark-mode.js` was changed to make dark mode the default.

### Screenshot

# Dark Mode:

image

# Light mode:
image

### How This PR Could Be Improved

- This prove could be improved by fixing the dark mode colors for the overlay card which is related to issue #65 

### Issue This PR Closes

This closes #48

### CODE REVIEW

**Comment by robzwolf** [comment]
Hey @Inoxia25! I just merged a bunch of PRs that look like they've caused a few conflicts 😢 Are you able to go through and try and correct those merge conflicts in this PR?

**Comment by Inoxia25** [comment]
@robzwolf yup just solved them

**Review by robzwolf — CHANGES_REQUESTED** [review]
I think something broke – the site seems to be permanently stuk in dark theme for me now in both Firefox and Chrome :(

**Comment by Inoxia25** [comment]
@robzwolf I think i messed up my code while solving the merge conflicts  :cry:  working on the changes

**Comment by Inoxia25** [comment]
@robzwolf made the changes! Could you please review it once again

**Review by robzwolf — APPROVED** [review]
Absolutely love this! It looks so good!

**Pull request merged**
