### PR TITLE
Added Github Stats and Most Used Languages

### LINKED ISSUE #29: Add GitHub Stats
Add a user's GitHub stats using something like this [GitHub action](https://github.com/jstrieb/github-stats) that auto generates SVGs that could be displayed in the About or a separate section.

### PR DESCRIPTION
**Pull request by Inoxia25**
### Why This PR Adds Value
This PR gives more idea about the users contributions and most used languages on Github

### What This PR Adds

- This PR adds a github stats card, which shows the the users commit history and contributions.
- This PR also adds a most languages card, which shows the 4 most used languages by the user on their Github Profile.

### Screenshot
Screenshot of portfolio

### Issue This PR Closes

This closes #29

### CODE REVIEW

**Review by louisefindlay23 — COMMENTED** [review]
Awesome job, @Inoxia25. Looks great. Love the most used languages card you added. On smaller screens, the cards are bunched together, so it would be good to add a margin in a media query to account for this. See image below.

Portfolio Github Stats card

If you wanted to extend it, maybe try and style the Github Stats card to match the colour scheme of the portfolio ?

**Comment by Inoxia25** [comment]
@louisefindlay23 hey changed the color scheme for the github stat card
image
do let me know if any other changes are required!

**Comment by louisefindlay23** [comment]
Awesome work on the colour scheme. Still see the margin issue. Will chat further in our 1 on 1.

**Comment by louisefindlay23** [comment]
That should be it resolved. Needed to be .github-stats img instead of the container class.

**Review by louisefindlay23 — APPROVED** [review]
That should be it resolved. :) Needed to be .github-stats img instead of the container class. Lovely conversation. Great to hear about your experiences and was great to chat about uni and hackathons.

**Comment by Inoxia25** [comment]
@louisefindlay23 yup it was so great talking to you! Thank you for all the recommendations!
I think we have got a conflicting issue in our config.yml file due to the github username change :cry:

**Comment by louisefindlay23** [comment]
Should be an easy fix. Will take a look after standup

**Comment by louisefindlay23** [comment]
Hmm, I can't look because I don't have write access or are PR author but basically install Refined Github then go to Extension Settings and generate a Github token, paste it into the field and then go to resolve conflicts in the web editor.

**Comment by louisefindlay23** [comment]
May do my talk on Git Merge Conflicts since it seems to be a topic of high interest and hopefully be very useful unless I learn some new and interesting new thing before then. Learned about ternary operators in JS but not sure if I can make a 10 min talk about it since I haven't had the change to use them yet.

**Comment by dtemir** [comment]
@Inoxia25 looks sharp. 

For the dark mode toggler, I think we should look into modifying the Vercel URL from 
`https://github-readme-stats.vercel.app/api?username=wrussell1999&show_icons=true&theme=default` to `https://github-readme-stats.vercel.app/api?username=wrussell1999&show_icons=true&theme=dark`, based on whether the dark mode is activated.

I'll wait until the PR gets merged and then try come up with a scrip to modify the url (feel free to try it too if you want)

**Review by robzwolf — APPROVED** [review]
Love it!

**Comment by Inoxia25** [comment]
@louisefindlay23 yes sounds like a plan! Who else to learn about git merge from than the git princess herself! :crown:

**Comment by Inoxia25** [comment]
@dtemir yup would look great! there are actually many themes available for the github stat card, so once we decide the color scheme for the dark mode, we can choose accordingly :eyes:

**Pull request merged**
