### PR TITLE
Added new colors to the dark mode

### LINKED ISSUE #44: Pick cool colors for Dark Mode
Right now, the dark mode is _ugly_, not gonna lie :smile: 
Website in Dark Mode
We need to pick new colors for the general color scheme. @jagnani73 suggested https://coolors.co/ to get a new palette.

So if somebody is interested in design and color picking, feel free to dive in `main.scss` and update those colors with new ideas! **You can also send-in your version to discord for our support :superhero:**

### LINKED ISSUE #48: Improving Dark Mode Toggle
Improve the current dark mode toggle. Currently, the toggle is at the left hand side with no space between it and the edge of the browser. There's also large text that's says enable Dark Mode.

- The toggle could be moved to the the top left similar to the navigation bar 

- The toggle switch could be modified to a sun and moon icon similar to this [article](https://dev.to/shadowscientist/making-a-dark-mode-switch-lightly-249j) - there's a Github repo and Codepen inside

### PR DESCRIPTION
**Pull request by dtemir**
### Why This PR Adds Value

Picked new colors for the dark mode with @Inoxia25 and @jagnani73 

### What This PR Adds

- It deletes the "Dark Mode" label
- It puts new colors for the dark mode 
- It changes **GitHub stats and most used languages** to dark when in dark mode
- It puts the toggler in the navbar

### Screenshot

Light Mode Website

Dark Mode Website

### How This PR Could Be Improved

- Make the toggler in the navbar look more natural
- Change the toggler style

### Issue This PR Closes

This closes #44

### CODE REVIEW

**Comment by dtemir** [comment]
- Resolved a merge conflict 
- Added what's in the main branch.

**Comment by dtemir** [comment]
Improved the PR a little. Hope it looks better. (Sorry for all those force-pushes, I don't know if they're bad for the commit history or for merging)

**Comment by dtemir** [comment]
Oh also put all the JavaScript stuff with the dark mode to `assets/js/dark-mode.js`

**Comment by prakharrathi25** [comment]
Hi, the dark mode colors look really good! Just a small thing to check. If you go to projects and click on one of the project overlay cards, you'll find that the colors don't change there. Maybe you could look into that? I had to select the text for it to be visible.  

Adding an image for reference
image

**Comment by dtemir** [comment]
@prakharrathi25 thanks for pointing that out! I'll take a look at it ASAP. I think the dark mode should change the color of the card, but that colors must be hard-coded in CSS.

**Comment by robzwolf** [comment]
Hey @dtemir, I'm going to merge this PR as-is because I want to keep them bite-size. If you'd like to fix the colours of the project modal, please open a separate PR :)

**Review by robzwolf — APPROVED** [review]
These colours look great!

**Pull request merged**
