### PR TITLE
added animation on hovering over the cards

### PR DESCRIPTION
**Pull request by Inoxia25**
### Why This PR Adds Value

This PR improves the user experience

### What This PR Adds

- on hovering over the cards (like for projects,experiences,etc), they expand to a slightly greater size, which I feel enhances the UX.

This closes issue #63

### CODE REVIEW

**Comment by dtemir** [comment]
@Inoxia25 is this something you meant in issue #63 ? Looks real good! Maybe you can add to it if you have more ideas from issue #63

**Comment by Inoxia25** [comment]
@dtemir yup earlier had mentioned even adding animation to the navbar links in issue #63 , but have created a separate issue for it now

**Comment by Inoxia25** [comment]
@robzwolf fixed all my merge conflicts! Please review the PR :smile:

**Review by robzwolf — APPROVED** [review]
Love it!

**Pull request merged**
