### PR TITLE
added about (bio) section, issue #6

### PR DESCRIPTION
**Pull request by MsMore**

### CODE REVIEW

**Comment by MsMore** [comment]
## Why this PR
Added a About me/Bio section in the existing index page, right below the profile section.

 ## Files added
 1. about.html
 2. about.scss
 3. about.yml
 
 image
 
 It is responsive to smaller viewports as well.
 
- The section is divided into two sub-sections; the `info` and the `bio` which are two separate div `child` inside one `about-section` div
- The responsiveness is defined in `about.scss` , using grid they have been stacked side-by-side and one top of another according to the screen size.
 
 ## Issue resolved
  This closes #6

**Comment by louisefindlay23** [comment]
This closes #6.

**Comment by louisefindlay23** [comment]
@MsMore, can you add This closes #6 in your original comment to link the issue to this PR? Just so it will auto-close the issue once the PR has been merged?

**Comment by MsMore** [comment]
Thanks @louisefindlay23 I learned something new today

**Review by louisefindlay23 — COMMENTED** [review]
Code looks great, @MsMore. Awesome job :)

Perhaps you can add some more padding or margins between the Hello there! and the text and maybe split the text up a bit into multiple paragraphs? That might just be personal preference though because I tend to like lots of space.

**Comment by MsMore** [comment]
@louisefindlay23 Yeah that's definitely a great idea, even I personally like it. Would Love to get your opinions on this one


image

**Comment by louisefindlay23** [comment]
Looks much better, @MsMore. Will be nicer for mobile users too. Is there an extra space before the initial letter of each paragraph?

**Comment by MsMore** [comment]
Yes @louisefindlay23, I added a tab character. Is it redundant?

**Comment by MsMore** [comment]
there is one small issue, if you noticed the border is black for all other `card` elements and not for the `about-section` I tried doing `border-color`, `border-width` but nothing seems to work. Also, I was no where able to find how the `card` got the `border-color` at the first place, is it some Bootstrap styling? Am I missing something

**Comment by louisefindlay23** [comment]
Thanks for posting in the PR, @MsMore. Makes it much easier to keep a track of.

**Comment by Primata** [comment]
@MsMore seems like every div container in _includes/files.html has a class "card-container". Could that resolve the issue?

**Comment by louisefindlay23** [comment]
From 1 on 1 call: I used the browser inspector and found the card div has another scss file `card.scss` from bootstrap styling. Adding the css border from that to the `all.scss` file's existing `.card` class should hopefully fix it.

```css
border: 1px solid rgba(0,0,0,.125);
```

**Comment by MsMore** [comment]
Thanks a lot for the quick 1-on-1 @louisefindlay23  and clearing the mess for me!

**Comment by louisefindlay23** [comment]
No problem. Glad it's sorted. Was great to chat.

**Review by robzwolf — APPROVED** [review]
Tested this locally and it looks great! Approved :rocket:

**Pull request merged**
