### PR TITLE
Improve PR Template

### LINKED ISSUE #15: Improve PR Template
Improve PR template by adding headings and prompts for more detail such as screenshots.

See #13 as an example.

### PR DESCRIPTION
**Pull request by louisefindlay23**
### Why This PR Adds Value

Improved Pull Request Template by adding headings and expanding on checklist. This guides fellows to ensure that PR descriptions are full of detail that aids other fellows that want to keep up to date on what's happening, perform peer reviewers and also pod leaders that provide final reviews.

### What This PR Adds

- Headings - adds markdown formatting so PR descriptions are clearly organised. Uses the existing checklist as a base.

- Images - adds the markdown syntax for a screenshot (to prompt fellows to provide an image so others don't have to checkout and build the PR to see what's changed visually). Also helps people that aren't used to Github's MD syntax

- Notes - provides handy hints and tips to what to add a PR description to add more detail and provides notes on how the MD syntax works

- PR Links - provides a guide on how to link issues to PRs since we (currently) don't have the correct permissions to do this through the GitHub UI. Means issues are automatically closed when the PR is merged and helps others find the PR linked to an issue.

### Screenshot

PR Template Image

### How This PR Could Be Improved

- **Contributions** - This PR could be improved by contributors adding new areas they think would be useful to include in a PR.

### Issue This PR Closes

This closes #15.

### CODE REVIEW

**Review by robzwolf — CHANGES_REQUESTED** [review]
The proposed changes look great, love to see a proper pull request template!

However, it looks like you included a bunch of commits in this PR that shouldn't be here (something related to testimonials?)

Can you remove them from this branch? Let me know if you need any help with that :)

**Comment by louisefindlay23** [comment]
Yeah. Sorry, @robzwolf. Forgot to branch off when doing multiple issues. Will fix now.

**Comment by louisefindlay23** [comment]
That should be it fixed, @robzwolf.

**Review by robzwolf — APPROVED** [review]
Looks good!

**Pull request merged**
