### PR TITLE
Added links to Navbar - Issue #7

### LINKED ISSUE #7: Add links to the Navbar
Add links to the navbar to navigate to the relevant sections (eg. projects, experience) of the page.
Also, it would be great if we can have an option to choose whether we want to make the navbar sticky or not.

### PR DESCRIPTION
**Pull request by ksaisudha24**
Added links to navbar to navigate to relevant sections

## What needs to be improved
- Make the navbar responsive
- Add option to choose to have a sticky bar

NavBar

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Great work, @ksaisudha24. Could you post a screenshot of the navbar so we can see what it looks like without checking out your PR?

**Comment by ksaisudha24** [comment]
@louisefindlay23 Thanks for the suggestion, I have uploaded the picture.

**Comment by louisefindlay23** [comment]
Thanks. That looks great.

**Review by robzwolf — CHANGES_REQUESTED** [review]
This looks fantastic on wide screens! However, on slightly narrower screens, the content overflows and a white bar appears. 

Do you think you're able to fix this? Let me know if you need any help with the CSS!

**Screenshot:**
image

**Comment by robzwolf** [comment]
Hey @ksaisudha24, looks like there are some conflicts on this Pull Request. Do you know how to fix them? Let me know if you need a hand!

**Comment by louisefindlay23** [comment]
Just posting here, @ksaisudha24 for reference. Having a 1 on 1. 

Because you can resolve these conflicts through the web editor, install the [Refined Github](https://github.com/sindresorhus/refined-github) browser extension which will add links (Keep Current Change, Accept Incoming Change, Use Both), which will make things a lot easier. The extension also adds lots of nice features to Github and improves the UI/UX.

**Comment by louisefindlay23** [comment]
That should be the merge conflicts resolved, @ksaisudha24. Great 1 on 1.

cc - @robzwolf

**Comment by ksaisudha24** [comment]
Thank you @louisefindlay23 for helping me resolve the merge conflicts

**Comment by ksaisudha24** [comment]
@robzwolf Both the content overflow and merge conflicts are fixed.

**Review by robzwolf — APPROVED** [review]
Looks good!

**Pull request merged**
