### PR TITLE
Added a contact form

### PR DESCRIPTION
**Pull request by anandrajaram21**
## Usefulness of this PR
- People need a way to interact with the visitors on their website, and a simple but effective solution is to add a contact form that the users can fill in, so as to know more about them.

## Changes made
- A contact section has been added at the bottom of the main page.
- A new `contact.html` file has been added with the content for the contact section

## How the form data looks on netlify
image

### CODE REVIEW

**Comment by louisefindlay23** [comment]
That's great, @anandrajaram21. Could you post a screenshot of the form so we can see what it looks like without checking out your PR and provide a link to the deployed version?

**Comment by anandrajaram21** [comment]
Absolutely, I'll add a screenshot of the form right now! As for the deployed version, I just created a new site on my personal netlify account from the fork of this repo, and tested the changes in production. I deleted the website soon after.

image

Please do give me some feedback on how the UI could be improved. I noticed that the template used bootstrap, so I just went ahead and used the usual bootstrap classes for the form elements.

**Comment by louisefindlay23** [comment]
Looks great, @anandrajaram21. 

If you want to extend it, I'd look into responsiveness (if it isn't already) and focus styles (especially for the button). Not sure what Netlify Forms does by default but it would be good to have some built-in form validation (styling any errors the browser shows - e.g. email format).

**Review by robzwolf — APPROVED** [review]
This is awesome stuff! If you'd like to make any further changes, please open a new PR.

**Pull request merged**
